export const FETCH_DATA = {
    SUCCESS: 'FETCH_DATA_SUCCESS',
    FAILED: 'FETCH_DATA_FAILED',
    LOADING: 'FETCH_DATA_LOADING'
}
export const CHOOSE_DATA = 'CHOOSE_DATA'
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY'
export const UPDATE_CURSOR_POSITION = "UPDATE_CURSOR_POSITION";
export const SET_CONTENT_DISPLAY = "SET_CONTENT_DISPLAY";
export const SET_MAP_PARAMETRS = "SET_MAP_PARAMETRS";
